defmodule Lumina.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Idempotent: apply changes only when not already present (avoids duplicate column/table from earlier migrations)
    execute fn ->
      repo = repo()
      # Add role to users if missing
      {:ok, users_info} = repo.query("PRAGMA table_info(users)")
      has_role = Enum.any?(users_info.rows, fn row -> Enum.at(row, 1) == "role" end)

      if not has_role do
        repo.query!("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user'")
      end

      # Create org_invites table and index if missing
      {:ok, tables} =
        repo.query("SELECT name FROM sqlite_master WHERE type='table' AND name='org_invites'")

      if tables.num_rows == 0 do
        repo.query!("""
        CREATE TABLE org_invites (
          id TEXT NOT NULL PRIMARY KEY,
          org_id TEXT NOT NULL REFERENCES orgs(id),
          token TEXT NOT NULL,
          role TEXT NOT NULL,
          expires_at TEXT NOT NULL,
          max_uses INTEGER,
          use_count INTEGER NOT NULL DEFAULT 0,
          inserted_at TEXT NOT NULL,
          updated_at TEXT NOT NULL
        )
        """)

        repo.query!("CREATE UNIQUE INDEX org_invites_unique_token_index ON org_invites (token)")
      else
        {:ok, idx} =
          repo.query(
            "SELECT name FROM sqlite_master WHERE type='index' AND name='org_invites_unique_token_index'"
          )

        if idx.num_rows == 0 do
          repo.query!("CREATE UNIQUE INDEX org_invites_unique_token_index ON org_invites (token)")
        end
      end
    end
  end

  def down do
    drop_if_exists unique_index(:org_invites, [:token], name: "org_invites_unique_token_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `org_invites` table without the `org_invites_org_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:org_invites)

    alter table(:users) do
      remove :role
    end
  end
end
