defmodule Lumina.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:share_links, [:org_id, :token],
                     name: "share_links_unique_token_index"
                   )

    create unique_index(:share_links, [:org_id, :token], name: "share_links_unique_token_index")
  end

  def down do
    drop_if_exists unique_index(:share_links, [:org_id, :token],
                     name: "share_links_unique_token_index"
                   )

    create unique_index(:share_links, [:org_id, :token], name: "share_links_unique_token_index")
  end
end