defmodule Lumina.Repo.Migrations.CreateMediaResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Create tables in dependency order: orgs first, then albums, then photos/share_links

    create table(:orgs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:orgs, [:slug], name: "orgs_unique_slug_index")

    create table(:org_memberships, primary_key: false) do
      add :org_id,
          references(:orgs, column: :id, name: "org_memberships_org_id_fkey", type: :uuid),
          null: false

      add :user_id,
          references(:users, column: :id, name: "org_memberships_user_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:org_memberships, [:user_id, :org_id],
             name: "org_memberships_unique_user_org_index"
           )

    create table(:albums, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :org_id, references(:orgs, column: :id, name: "albums_org_id_fkey", type: :uuid),
        null: false

      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:photos, primary_key: false) do
      add :uploaded_by_id,
          references(:users, column: :id, name: "photos_uploaded_by_id_fkey", type: :uuid)

      add :album_id,
          references(:albums,
            column: :id,
            name: "photos_album_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :org_id, references(:orgs, column: :id, name: "photos_org_id_fkey", type: :uuid),
        null: false

      add :tags, {:array, :text}, default: []
      add :content_type, :text
      add :file_size, :bigint
      add :thumbnail_path, :text, null: false
      add :original_path, :text, null: false
      add :filename, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:share_links, primary_key: false) do
      add :created_by_id,
          references(:users, column: :id, name: "share_links_created_by_id_fkey", type: :uuid)

      add :album_id,
          references(:albums,
            column: :id,
            name: "share_links_album_id_fkey",
            type: :uuid
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false

      add :org_id, references(:orgs, column: :id, name: "share_links_org_id_fkey", type: :uuid),
        null: false

      add :photo_ids, {:array, :uuid}, default: []
      add :max_views, :bigint
      add :view_count, :bigint
      add :expires_at, :utc_datetime, null: false
      add :password_hash, :text
      add :token, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:share_links, [:org_id, :token], name: "share_links_unique_token_index")
  end

  def down do
    drop_if_exists unique_index(:share_links, [:org_id, :token],
                     name: "share_links_unique_token_index"
                   )

    drop table(:share_links)
    drop table(:photos)
    drop table(:albums)

    drop_if_exists unique_index(:org_memberships, [:user_id, :org_id],
                     name: "org_memberships_unique_user_org_index"
                   )

    drop table(:org_memberships)

    drop_if_exists unique_index(:orgs, [:slug], name: "orgs_unique_slug_index")

    drop table(:orgs)
  end
end
